// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {
        "schemas": {
            "core.AuthenticatedUser": {
                "properties": {
                    "activeWorkspaceId": {
                        "type": "string"
                    },
                    "activeWorkspaceName": {
                        "type": "string"
                    },
                    "activeWorkspaceRoles": {
                        "items": {
                            "$ref": "#/components/schemas/core.WorkspaceRole"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "avatar": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "scope": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "core.WorkspaceRole": {
                "enum": [
                    "owner",
                    "admin",
                    "member"
                ],
                "type": "string",
                "x-enum-varnames": [
                    "WorkspaceRoleOwner",
                    "WorkspaceRoleAdmin",
                    "WorkspaceRoleMember"
                ]
            },
            "httpx.ErrorBody": {
                "properties": {
                    "code": {
                        "type": "string"
                    },
                    "fields": {
                        "items": {
                            "$ref": "#/components/schemas/httpx.FieldError"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "message": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "httpx.ErrorResponse": {
                "properties": {
                    "error": {
                        "$ref": "#/components/schemas/httpx.ErrorBody"
                    },
                    "meta": {
                        "$ref": "#/components/schemas/httpx.Meta"
                    }
                },
                "type": "object"
            },
            "httpx.FieldError": {
                "properties": {
                    "field": {
                        "type": "string"
                    },
                    "rule": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "httpx.Meta": {
                "properties": {
                    "cursor": {
                        "type": "string"
                    },
                    "requestId": {
                        "type": "string"
                    },
                    "timestamp": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "httpx.WebResponse-core_AuthenticatedUser": {
                "properties": {
                    "data": {
                        "$ref": "#/components/schemas/core.AuthenticatedUser"
                    },
                    "meta": {
                        "$ref": "#/components/schemas/httpx.Meta"
                    }
                },
                "type": "object"
            }
        },
        "securitySchemes": {
            "BearerAuth": {
                "description": "Type \"Bearer\" followed by a space and JWT token.",
                "in": "header",
                "name": "Authorization",
                "type": "apiKey"
            }
        }
    },
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "externalDocs": {
        "description": "",
        "url": ""
    },
    "paths": {
        "/ping": {
            "get": {
                "description": "Returns current authenticated user information from context",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/httpx.WebResponse-core_AuthenticatedUser"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/httpx.ErrorResponse"
                                }
                            }
                        },
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "summary": "Health check ping",
                "tags": [
                    "Health"
                ]
            }
        }
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "url": "https://api.pkrbt.id/"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Title:            "Domus API",
	Description:      "Domus API Server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
