// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/paroki/domus/api/ent/diocese"
	"github.com/paroki/domus/api/ent/internal"
	"github.com/paroki/domus/api/ent/parish"
	"github.com/paroki/domus/api/ent/predicate"
	"github.com/paroki/domus/api/ent/user"
)

// DioceseUpdate is the builder for updating Diocese entities.
type DioceseUpdate struct {
	config
	hooks    []Hook
	mutation *DioceseMutation
}

// Where appends a list predicates to the DioceseUpdate builder.
func (_u *DioceseUpdate) Where(ps ...predicate.Diocese) *DioceseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedBy sets the "createdBy" field.
func (_u *DioceseUpdate) SetCreatedBy(v uuid.UUID) *DioceseUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "createdBy" field if the given value is not nil.
func (_u *DioceseUpdate) SetNillableCreatedBy(v *uuid.UUID) *DioceseUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updatedBy" field.
func (_u *DioceseUpdate) SetUpdatedBy(v uuid.UUID) *DioceseUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updatedBy" field if the given value is not nil.
func (_u *DioceseUpdate) SetNillableUpdatedBy(v *uuid.UUID) *DioceseUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *DioceseUpdate) SetUpdatedAt(v time.Time) *DioceseUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *DioceseUpdate) SetName(v string) *DioceseUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DioceseUpdate) SetNillableName(v *string) *DioceseUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *DioceseUpdate) SetCreatorID(id uuid.UUID) *DioceseUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *DioceseUpdate) SetCreator(v *User) *DioceseUpdate {
	return _u.SetCreatorID(v.ID)
}

// SetUpdaterID sets the "updater" edge to the User entity by ID.
func (_u *DioceseUpdate) SetUpdaterID(id uuid.UUID) *DioceseUpdate {
	_u.mutation.SetUpdaterID(id)
	return _u
}

// SetUpdater sets the "updater" edge to the User entity.
func (_u *DioceseUpdate) SetUpdater(v *User) *DioceseUpdate {
	return _u.SetUpdaterID(v.ID)
}

// AddParishIDs adds the "parishes" edge to the Parish entity by IDs.
func (_u *DioceseUpdate) AddParishIDs(ids ...int) *DioceseUpdate {
	_u.mutation.AddParishIDs(ids...)
	return _u
}

// AddParishes adds the "parishes" edges to the Parish entity.
func (_u *DioceseUpdate) AddParishes(v ...*Parish) *DioceseUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParishIDs(ids...)
}

// Mutation returns the DioceseMutation object of the builder.
func (_u *DioceseUpdate) Mutation() *DioceseMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *DioceseUpdate) ClearCreator() *DioceseUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// ClearUpdater clears the "updater" edge to the User entity.
func (_u *DioceseUpdate) ClearUpdater() *DioceseUpdate {
	_u.mutation.ClearUpdater()
	return _u
}

// ClearParishes clears all "parishes" edges to the Parish entity.
func (_u *DioceseUpdate) ClearParishes() *DioceseUpdate {
	_u.mutation.ClearParishes()
	return _u
}

// RemoveParishIDs removes the "parishes" edge to Parish entities by IDs.
func (_u *DioceseUpdate) RemoveParishIDs(ids ...int) *DioceseUpdate {
	_u.mutation.RemoveParishIDs(ids...)
	return _u
}

// RemoveParishes removes "parishes" edges to Parish entities.
func (_u *DioceseUpdate) RemoveParishes(v ...*Parish) *DioceseUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParishIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DioceseUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DioceseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DioceseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DioceseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DioceseUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := diocese.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DioceseUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := diocese.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Diocese.name": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Diocese.creator"`)
	}
	if _u.mutation.UpdaterCleared() && len(_u.mutation.UpdaterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Diocese.updater"`)
	}
	return nil
}

func (_u *DioceseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(diocese.Table, diocese.Columns, sqlgraph.NewFieldSpec(diocese.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(diocese.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(diocese.FieldName, field.TypeString, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   diocese.CreatorTable,
			Columns: []string{diocese.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Diocese
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   diocese.CreatorTable,
			Columns: []string{diocese.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Diocese
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UpdaterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   diocese.UpdaterTable,
			Columns: []string{diocese.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Diocese
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpdaterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   diocese.UpdaterTable,
			Columns: []string{diocese.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Diocese
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParishesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   diocese.ParishesTable,
			Columns: []string{diocese.ParishesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(parish.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Parish
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParishesIDs(); len(nodes) > 0 && !_u.mutation.ParishesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   diocese.ParishesTable,
			Columns: []string{diocese.ParishesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(parish.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Parish
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParishesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   diocese.ParishesTable,
			Columns: []string{diocese.ParishesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(parish.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Parish
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Diocese
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{diocese.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DioceseUpdateOne is the builder for updating a single Diocese entity.
type DioceseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DioceseMutation
}

// SetCreatedBy sets the "createdBy" field.
func (_u *DioceseUpdateOne) SetCreatedBy(v uuid.UUID) *DioceseUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "createdBy" field if the given value is not nil.
func (_u *DioceseUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *DioceseUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updatedBy" field.
func (_u *DioceseUpdateOne) SetUpdatedBy(v uuid.UUID) *DioceseUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updatedBy" field if the given value is not nil.
func (_u *DioceseUpdateOne) SetNillableUpdatedBy(v *uuid.UUID) *DioceseUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *DioceseUpdateOne) SetUpdatedAt(v time.Time) *DioceseUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *DioceseUpdateOne) SetName(v string) *DioceseUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DioceseUpdateOne) SetNillableName(v *string) *DioceseUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *DioceseUpdateOne) SetCreatorID(id uuid.UUID) *DioceseUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *DioceseUpdateOne) SetCreator(v *User) *DioceseUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// SetUpdaterID sets the "updater" edge to the User entity by ID.
func (_u *DioceseUpdateOne) SetUpdaterID(id uuid.UUID) *DioceseUpdateOne {
	_u.mutation.SetUpdaterID(id)
	return _u
}

// SetUpdater sets the "updater" edge to the User entity.
func (_u *DioceseUpdateOne) SetUpdater(v *User) *DioceseUpdateOne {
	return _u.SetUpdaterID(v.ID)
}

// AddParishIDs adds the "parishes" edge to the Parish entity by IDs.
func (_u *DioceseUpdateOne) AddParishIDs(ids ...int) *DioceseUpdateOne {
	_u.mutation.AddParishIDs(ids...)
	return _u
}

// AddParishes adds the "parishes" edges to the Parish entity.
func (_u *DioceseUpdateOne) AddParishes(v ...*Parish) *DioceseUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParishIDs(ids...)
}

// Mutation returns the DioceseMutation object of the builder.
func (_u *DioceseUpdateOne) Mutation() *DioceseMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *DioceseUpdateOne) ClearCreator() *DioceseUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// ClearUpdater clears the "updater" edge to the User entity.
func (_u *DioceseUpdateOne) ClearUpdater() *DioceseUpdateOne {
	_u.mutation.ClearUpdater()
	return _u
}

// ClearParishes clears all "parishes" edges to the Parish entity.
func (_u *DioceseUpdateOne) ClearParishes() *DioceseUpdateOne {
	_u.mutation.ClearParishes()
	return _u
}

// RemoveParishIDs removes the "parishes" edge to Parish entities by IDs.
func (_u *DioceseUpdateOne) RemoveParishIDs(ids ...int) *DioceseUpdateOne {
	_u.mutation.RemoveParishIDs(ids...)
	return _u
}

// RemoveParishes removes "parishes" edges to Parish entities.
func (_u *DioceseUpdateOne) RemoveParishes(v ...*Parish) *DioceseUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParishIDs(ids...)
}

// Where appends a list predicates to the DioceseUpdate builder.
func (_u *DioceseUpdateOne) Where(ps ...predicate.Diocese) *DioceseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DioceseUpdateOne) Select(field string, fields ...string) *DioceseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Diocese entity.
func (_u *DioceseUpdateOne) Save(ctx context.Context) (*Diocese, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DioceseUpdateOne) SaveX(ctx context.Context) *Diocese {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DioceseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DioceseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DioceseUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := diocese.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DioceseUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := diocese.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Diocese.name": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Diocese.creator"`)
	}
	if _u.mutation.UpdaterCleared() && len(_u.mutation.UpdaterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Diocese.updater"`)
	}
	return nil
}

func (_u *DioceseUpdateOne) sqlSave(ctx context.Context) (_node *Diocese, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(diocese.Table, diocese.Columns, sqlgraph.NewFieldSpec(diocese.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Diocese.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, diocese.FieldID)
		for _, f := range fields {
			if !diocese.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != diocese.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(diocese.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(diocese.FieldName, field.TypeString, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   diocese.CreatorTable,
			Columns: []string{diocese.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Diocese
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   diocese.CreatorTable,
			Columns: []string{diocese.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Diocese
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UpdaterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   diocese.UpdaterTable,
			Columns: []string{diocese.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Diocese
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpdaterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   diocese.UpdaterTable,
			Columns: []string{diocese.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Diocese
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParishesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   diocese.ParishesTable,
			Columns: []string{diocese.ParishesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(parish.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Parish
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParishesIDs(); len(nodes) > 0 && !_u.mutation.ParishesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   diocese.ParishesTable,
			Columns: []string{diocese.ParishesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(parish.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Parish
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParishesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   diocese.ParishesTable,
			Columns: []string{diocese.ParishesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(parish.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Parish
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Diocese
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Diocese{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{diocese.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
