// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/paroki/domus/api/ent/diocese"
	"github.com/paroki/domus/api/ent/parish"
	"github.com/paroki/domus/api/ent/user"
)

// DioceseCreate is the builder for creating a Diocese entity.
type DioceseCreate struct {
	config
	mutation *DioceseMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedBy sets the "createdBy" field.
func (_c *DioceseCreate) SetCreatedBy(v uuid.UUID) *DioceseCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "createdAt" field.
func (_c *DioceseCreate) SetCreatedAt(v time.Time) *DioceseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_c *DioceseCreate) SetNillableCreatedAt(v *time.Time) *DioceseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updatedBy" field.
func (_c *DioceseCreate) SetUpdatedBy(v uuid.UUID) *DioceseCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetUpdatedAt sets the "updatedAt" field.
func (_c *DioceseCreate) SetUpdatedAt(v time.Time) *DioceseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (_c *DioceseCreate) SetNillableUpdatedAt(v *time.Time) *DioceseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *DioceseCreate) SetName(v string) *DioceseCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetID sets the "id" field.
func (_c *DioceseCreate) SetID(v int) *DioceseCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_c *DioceseCreate) SetCreatorID(id uuid.UUID) *DioceseCreate {
	_c.mutation.SetCreatorID(id)
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *DioceseCreate) SetCreator(v *User) *DioceseCreate {
	return _c.SetCreatorID(v.ID)
}

// SetUpdaterID sets the "updater" edge to the User entity by ID.
func (_c *DioceseCreate) SetUpdaterID(id uuid.UUID) *DioceseCreate {
	_c.mutation.SetUpdaterID(id)
	return _c
}

// SetUpdater sets the "updater" edge to the User entity.
func (_c *DioceseCreate) SetUpdater(v *User) *DioceseCreate {
	return _c.SetUpdaterID(v.ID)
}

// AddParishIDs adds the "parishes" edge to the Parish entity by IDs.
func (_c *DioceseCreate) AddParishIDs(ids ...int) *DioceseCreate {
	_c.mutation.AddParishIDs(ids...)
	return _c
}

// AddParishes adds the "parishes" edges to the Parish entity.
func (_c *DioceseCreate) AddParishes(v ...*Parish) *DioceseCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddParishIDs(ids...)
}

// Mutation returns the DioceseMutation object of the builder.
func (_c *DioceseCreate) Mutation() *DioceseMutation {
	return _c.mutation
}

// Save creates the Diocese in the database.
func (_c *DioceseCreate) Save(ctx context.Context) (*Diocese, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DioceseCreate) SaveX(ctx context.Context) *Diocese {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DioceseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DioceseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DioceseCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := diocese.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := diocese.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DioceseCreate) check() error {
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "createdBy", err: errors.New(`ent: missing required field "Diocese.createdBy"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "Diocese.createdAt"`)}
	}
	if _, ok := _c.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updatedBy", err: errors.New(`ent: missing required field "Diocese.updatedBy"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "Diocese.updatedAt"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Diocese.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := diocese.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Diocese.name": %w`, err)}
		}
	}
	if len(_c.mutation.CreatorIDs()) == 0 {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required edge "Diocese.creator"`)}
	}
	if len(_c.mutation.UpdaterIDs()) == 0 {
		return &ValidationError{Name: "updater", err: errors.New(`ent: missing required edge "Diocese.updater"`)}
	}
	return nil
}

func (_c *DioceseCreate) sqlSave(ctx context.Context) (*Diocese, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DioceseCreate) createSpec() (*Diocese, *sqlgraph.CreateSpec) {
	var (
		_node = &Diocese{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(diocese.Table, sqlgraph.NewFieldSpec(diocese.FieldID, field.TypeInt))
	)
	_spec.Schema = _c.schemaConfig.Diocese
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(diocese.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(diocese.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(diocese.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   diocese.CreatorTable,
			Columns: []string{diocese.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _c.schemaConfig.Diocese
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UpdaterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   diocese.UpdaterTable,
			Columns: []string{diocese.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _c.schemaConfig.Diocese
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UpdatedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParishesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   diocese.ParishesTable,
			Columns: []string{diocese.ParishesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(parish.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _c.schemaConfig.Parish
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Diocese.Create().
//		SetCreatedBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DioceseUpsert) {
//			SetCreatedBy(v+v).
//		}).
//		Exec(ctx)
func (_c *DioceseCreate) OnConflict(opts ...sql.ConflictOption) *DioceseUpsertOne {
	_c.conflict = opts
	return &DioceseUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Diocese.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DioceseCreate) OnConflictColumns(columns ...string) *DioceseUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DioceseUpsertOne{
		create: _c,
	}
}

type (
	// DioceseUpsertOne is the builder for "upsert"-ing
	//  one Diocese node.
	DioceseUpsertOne struct {
		create *DioceseCreate
	}

	// DioceseUpsert is the "OnConflict" setter.
	DioceseUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedBy sets the "createdBy" field.
func (u *DioceseUpsert) SetCreatedBy(v uuid.UUID) *DioceseUpsert {
	u.Set(diocese.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "createdBy" field to the value that was provided on create.
func (u *DioceseUpsert) UpdateCreatedBy() *DioceseUpsert {
	u.SetExcluded(diocese.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updatedBy" field.
func (u *DioceseUpsert) SetUpdatedBy(v uuid.UUID) *DioceseUpsert {
	u.Set(diocese.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updatedBy" field to the value that was provided on create.
func (u *DioceseUpsert) UpdateUpdatedBy() *DioceseUpsert {
	u.SetExcluded(diocese.FieldUpdatedBy)
	return u
}

// SetUpdatedAt sets the "updatedAt" field.
func (u *DioceseUpsert) SetUpdatedAt(v time.Time) *DioceseUpsert {
	u.Set(diocese.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updatedAt" field to the value that was provided on create.
func (u *DioceseUpsert) UpdateUpdatedAt() *DioceseUpsert {
	u.SetExcluded(diocese.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *DioceseUpsert) SetName(v string) *DioceseUpsert {
	u.Set(diocese.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DioceseUpsert) UpdateName() *DioceseUpsert {
	u.SetExcluded(diocese.FieldName)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Diocese.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(diocese.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DioceseUpsertOne) UpdateNewValues() *DioceseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(diocese.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(diocese.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Diocese.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DioceseUpsertOne) Ignore() *DioceseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DioceseUpsertOne) DoNothing() *DioceseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DioceseCreate.OnConflict
// documentation for more info.
func (u *DioceseUpsertOne) Update(set func(*DioceseUpsert)) *DioceseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DioceseUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedBy sets the "createdBy" field.
func (u *DioceseUpsertOne) SetCreatedBy(v uuid.UUID) *DioceseUpsertOne {
	return u.Update(func(s *DioceseUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "createdBy" field to the value that was provided on create.
func (u *DioceseUpsertOne) UpdateCreatedBy() *DioceseUpsertOne {
	return u.Update(func(s *DioceseUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedBy sets the "updatedBy" field.
func (u *DioceseUpsertOne) SetUpdatedBy(v uuid.UUID) *DioceseUpsertOne {
	return u.Update(func(s *DioceseUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updatedBy" field to the value that was provided on create.
func (u *DioceseUpsertOne) UpdateUpdatedBy() *DioceseUpsertOne {
	return u.Update(func(s *DioceseUpsert) {
		s.UpdateUpdatedBy()
	})
}

// SetUpdatedAt sets the "updatedAt" field.
func (u *DioceseUpsertOne) SetUpdatedAt(v time.Time) *DioceseUpsertOne {
	return u.Update(func(s *DioceseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updatedAt" field to the value that was provided on create.
func (u *DioceseUpsertOne) UpdateUpdatedAt() *DioceseUpsertOne {
	return u.Update(func(s *DioceseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *DioceseUpsertOne) SetName(v string) *DioceseUpsertOne {
	return u.Update(func(s *DioceseUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DioceseUpsertOne) UpdateName() *DioceseUpsertOne {
	return u.Update(func(s *DioceseUpsert) {
		s.UpdateName()
	})
}

// Exec executes the query.
func (u *DioceseUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DioceseCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DioceseUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DioceseUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DioceseUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DioceseCreateBulk is the builder for creating many Diocese entities in bulk.
type DioceseCreateBulk struct {
	config
	err      error
	builders []*DioceseCreate
	conflict []sql.ConflictOption
}

// Save creates the Diocese entities in the database.
func (_c *DioceseCreateBulk) Save(ctx context.Context) ([]*Diocese, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Diocese, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DioceseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DioceseCreateBulk) SaveX(ctx context.Context) []*Diocese {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DioceseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DioceseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Diocese.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DioceseUpsert) {
//			SetCreatedBy(v+v).
//		}).
//		Exec(ctx)
func (_c *DioceseCreateBulk) OnConflict(opts ...sql.ConflictOption) *DioceseUpsertBulk {
	_c.conflict = opts
	return &DioceseUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Diocese.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DioceseCreateBulk) OnConflictColumns(columns ...string) *DioceseUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DioceseUpsertBulk{
		create: _c,
	}
}

// DioceseUpsertBulk is the builder for "upsert"-ing
// a bulk of Diocese nodes.
type DioceseUpsertBulk struct {
	create *DioceseCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Diocese.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(diocese.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DioceseUpsertBulk) UpdateNewValues() *DioceseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(diocese.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(diocese.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Diocese.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DioceseUpsertBulk) Ignore() *DioceseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DioceseUpsertBulk) DoNothing() *DioceseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DioceseCreateBulk.OnConflict
// documentation for more info.
func (u *DioceseUpsertBulk) Update(set func(*DioceseUpsert)) *DioceseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DioceseUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedBy sets the "createdBy" field.
func (u *DioceseUpsertBulk) SetCreatedBy(v uuid.UUID) *DioceseUpsertBulk {
	return u.Update(func(s *DioceseUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "createdBy" field to the value that was provided on create.
func (u *DioceseUpsertBulk) UpdateCreatedBy() *DioceseUpsertBulk {
	return u.Update(func(s *DioceseUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedBy sets the "updatedBy" field.
func (u *DioceseUpsertBulk) SetUpdatedBy(v uuid.UUID) *DioceseUpsertBulk {
	return u.Update(func(s *DioceseUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updatedBy" field to the value that was provided on create.
func (u *DioceseUpsertBulk) UpdateUpdatedBy() *DioceseUpsertBulk {
	return u.Update(func(s *DioceseUpsert) {
		s.UpdateUpdatedBy()
	})
}

// SetUpdatedAt sets the "updatedAt" field.
func (u *DioceseUpsertBulk) SetUpdatedAt(v time.Time) *DioceseUpsertBulk {
	return u.Update(func(s *DioceseUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updatedAt" field to the value that was provided on create.
func (u *DioceseUpsertBulk) UpdateUpdatedAt() *DioceseUpsertBulk {
	return u.Update(func(s *DioceseUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *DioceseUpsertBulk) SetName(v string) *DioceseUpsertBulk {
	return u.Update(func(s *DioceseUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DioceseUpsertBulk) UpdateName() *DioceseUpsertBulk {
	return u.Update(func(s *DioceseUpsert) {
		s.UpdateName()
	})
}

// Exec executes the query.
func (u *DioceseUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DioceseCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DioceseCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DioceseUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
