// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/paroki/domus/api/ent/internal"
	"github.com/paroki/domus/api/ent/membership"
	"github.com/paroki/domus/api/ent/predicate"
)

// MembershipUpdate is the builder for updating Membership entities.
type MembershipUpdate struct {
	config
	hooks    []Hook
	mutation *MembershipMutation
}

// Where appends a list predicates to the MembershipUpdate builder.
func (_u *MembershipUpdate) Where(ps ...predicate.Membership) *MembershipUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *MembershipUpdate) SetUserID(v string) *MembershipUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MembershipUpdate) SetNillableUserID(v *string) *MembershipUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetScopeType sets the "scope_type" field.
func (_u *MembershipUpdate) SetScopeType(v membership.ScopeType) *MembershipUpdate {
	_u.mutation.SetScopeType(v)
	return _u
}

// SetNillableScopeType sets the "scope_type" field if the given value is not nil.
func (_u *MembershipUpdate) SetNillableScopeType(v *membership.ScopeType) *MembershipUpdate {
	if v != nil {
		_u.SetScopeType(*v)
	}
	return _u
}

// SetScopeID sets the "scope_id" field.
func (_u *MembershipUpdate) SetScopeID(v int64) *MembershipUpdate {
	_u.mutation.ResetScopeID()
	_u.mutation.SetScopeID(v)
	return _u
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_u *MembershipUpdate) SetNillableScopeID(v *int64) *MembershipUpdate {
	if v != nil {
		_u.SetScopeID(*v)
	}
	return _u
}

// AddScopeID adds value to the "scope_id" field.
func (_u *MembershipUpdate) AddScopeID(v int64) *MembershipUpdate {
	_u.mutation.AddScopeID(v)
	return _u
}

// SetRole sets the "role" field.
func (_u *MembershipUpdate) SetRole(v membership.Role) *MembershipUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *MembershipUpdate) SetNillableRole(v *membership.Role) *MembershipUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// Mutation returns the MembershipMutation object of the builder.
func (_u *MembershipUpdate) Mutation() *MembershipMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MembershipUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MembershipUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MembershipUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MembershipUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MembershipUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := membership.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Membership.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScopeType(); ok {
		if err := membership.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "Membership.scope_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScopeID(); ok {
		if err := membership.ScopeIDValidator(v); err != nil {
			return &ValidationError{Name: "scope_id", err: fmt.Errorf(`ent: validator failed for field "Membership.scope_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := membership.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Membership.role": %w`, err)}
		}
	}
	return nil
}

func (_u *MembershipUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(membership.Table, membership.Columns, sqlgraph.NewFieldSpec(membership.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(membership.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeType(); ok {
		_spec.SetField(membership.FieldScopeType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScopeID(); ok {
		_spec.SetField(membership.FieldScopeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedScopeID(); ok {
		_spec.AddField(membership.FieldScopeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(membership.FieldRole, field.TypeEnum, value)
	}
	_spec.Node.Schema = _u.schemaConfig.Membership
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{membership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MembershipUpdateOne is the builder for updating a single Membership entity.
type MembershipUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MembershipMutation
}

// SetUserID sets the "user_id" field.
func (_u *MembershipUpdateOne) SetUserID(v string) *MembershipUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *MembershipUpdateOne) SetNillableUserID(v *string) *MembershipUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetScopeType sets the "scope_type" field.
func (_u *MembershipUpdateOne) SetScopeType(v membership.ScopeType) *MembershipUpdateOne {
	_u.mutation.SetScopeType(v)
	return _u
}

// SetNillableScopeType sets the "scope_type" field if the given value is not nil.
func (_u *MembershipUpdateOne) SetNillableScopeType(v *membership.ScopeType) *MembershipUpdateOne {
	if v != nil {
		_u.SetScopeType(*v)
	}
	return _u
}

// SetScopeID sets the "scope_id" field.
func (_u *MembershipUpdateOne) SetScopeID(v int64) *MembershipUpdateOne {
	_u.mutation.ResetScopeID()
	_u.mutation.SetScopeID(v)
	return _u
}

// SetNillableScopeID sets the "scope_id" field if the given value is not nil.
func (_u *MembershipUpdateOne) SetNillableScopeID(v *int64) *MembershipUpdateOne {
	if v != nil {
		_u.SetScopeID(*v)
	}
	return _u
}

// AddScopeID adds value to the "scope_id" field.
func (_u *MembershipUpdateOne) AddScopeID(v int64) *MembershipUpdateOne {
	_u.mutation.AddScopeID(v)
	return _u
}

// SetRole sets the "role" field.
func (_u *MembershipUpdateOne) SetRole(v membership.Role) *MembershipUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *MembershipUpdateOne) SetNillableRole(v *membership.Role) *MembershipUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// Mutation returns the MembershipMutation object of the builder.
func (_u *MembershipUpdateOne) Mutation() *MembershipMutation {
	return _u.mutation
}

// Where appends a list predicates to the MembershipUpdate builder.
func (_u *MembershipUpdateOne) Where(ps ...predicate.Membership) *MembershipUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MembershipUpdateOne) Select(field string, fields ...string) *MembershipUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Membership entity.
func (_u *MembershipUpdateOne) Save(ctx context.Context) (*Membership, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MembershipUpdateOne) SaveX(ctx context.Context) *Membership {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MembershipUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MembershipUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MembershipUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := membership.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Membership.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScopeType(); ok {
		if err := membership.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "Membership.scope_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScopeID(); ok {
		if err := membership.ScopeIDValidator(v); err != nil {
			return &ValidationError{Name: "scope_id", err: fmt.Errorf(`ent: validator failed for field "Membership.scope_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := membership.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Membership.role": %w`, err)}
		}
	}
	return nil
}

func (_u *MembershipUpdateOne) sqlSave(ctx context.Context) (_node *Membership, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(membership.Table, membership.Columns, sqlgraph.NewFieldSpec(membership.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Membership.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, membership.FieldID)
		for _, f := range fields {
			if !membership.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != membership.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(membership.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeType(); ok {
		_spec.SetField(membership.FieldScopeType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ScopeID(); ok {
		_spec.SetField(membership.FieldScopeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedScopeID(); ok {
		_spec.AddField(membership.FieldScopeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(membership.FieldRole, field.TypeEnum, value)
	}
	_spec.Node.Schema = _u.schemaConfig.Membership
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Membership{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{membership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
