// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/paroki/domus/api/ent/diocese"
	"github.com/paroki/domus/api/ent/parish"
)

// Parish is the model entity for the Parish schema.
type Parish struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ParishQuery when eager-loading is set.
	Edges            ParishEdges `json:"edges"`
	diocese_parishes *int
	selectValues     sql.SelectValues
}

// ParishEdges holds the relations/edges for other nodes in the graph.
type ParishEdges struct {
	// Diocese holds the value of the diocese edge.
	Diocese *Diocese `json:"diocese,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DioceseOrErr returns the Diocese value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ParishEdges) DioceseOrErr() (*Diocese, error) {
	if e.Diocese != nil {
		return e.Diocese, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: diocese.Label}
	}
	return nil, &NotLoadedError{edge: "diocese"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Parish) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case parish.FieldID:
			values[i] = new(sql.NullInt64)
		case parish.FieldName:
			values[i] = new(sql.NullString)
		case parish.ForeignKeys[0]: // diocese_parishes
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Parish fields.
func (_m *Parish) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case parish.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case parish.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case parish.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field diocese_parishes", value)
			} else if value.Valid {
				_m.diocese_parishes = new(int)
				*_m.diocese_parishes = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Parish.
// This includes values selected through modifiers, order, etc.
func (_m *Parish) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDiocese queries the "diocese" edge of the Parish entity.
func (_m *Parish) QueryDiocese() *DioceseQuery {
	return NewParishClient(_m.config).QueryDiocese(_m)
}

// Update returns a builder for updating this Parish.
// Note that you need to call Parish.Unwrap() before calling this method if this Parish
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Parish) Update() *ParishUpdateOne {
	return NewParishClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Parish entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Parish) Unwrap() *Parish {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Parish is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Parish) String() string {
	var builder strings.Builder
	builder.WriteString("Parish(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Parishes is a parsable slice of Parish.
type Parishes []*Parish
