// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/paroki/domus/api/ent/diocese"
	"github.com/paroki/domus/api/ent/parish"
)

// ParishCreate is the builder for creating a Parish entity.
type ParishCreate struct {
	config
	mutation *ParishMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *ParishCreate) SetName(v string) *ParishCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ParishCreate) SetID(v int) *ParishCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetDioceseID sets the "diocese" edge to the Diocese entity by ID.
func (_c *ParishCreate) SetDioceseID(id int) *ParishCreate {
	_c.mutation.SetDioceseID(id)
	return _c
}

// SetNillableDioceseID sets the "diocese" edge to the Diocese entity by ID if the given value is not nil.
func (_c *ParishCreate) SetNillableDioceseID(id *int) *ParishCreate {
	if id != nil {
		_c = _c.SetDioceseID(*id)
	}
	return _c
}

// SetDiocese sets the "diocese" edge to the Diocese entity.
func (_c *ParishCreate) SetDiocese(v *Diocese) *ParishCreate {
	return _c.SetDioceseID(v.ID)
}

// Mutation returns the ParishMutation object of the builder.
func (_c *ParishCreate) Mutation() *ParishMutation {
	return _c.mutation
}

// Save creates the Parish in the database.
func (_c *ParishCreate) Save(ctx context.Context) (*Parish, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ParishCreate) SaveX(ctx context.Context) *Parish {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ParishCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ParishCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ParishCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Parish.name"`)}
	}
	return nil
}

func (_c *ParishCreate) sqlSave(ctx context.Context) (*Parish, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ParishCreate) createSpec() (*Parish, *sqlgraph.CreateSpec) {
	var (
		_node = &Parish{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(parish.Table, sqlgraph.NewFieldSpec(parish.FieldID, field.TypeInt))
	)
	_spec.Schema = _c.schemaConfig.Parish
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(parish.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := _c.mutation.DioceseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   parish.DioceseTable,
			Columns: []string{parish.DioceseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diocese.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _c.schemaConfig.Parish
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.diocese_parishes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Parish.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ParishUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *ParishCreate) OnConflict(opts ...sql.ConflictOption) *ParishUpsertOne {
	_c.conflict = opts
	return &ParishUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Parish.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ParishCreate) OnConflictColumns(columns ...string) *ParishUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ParishUpsertOne{
		create: _c,
	}
}

type (
	// ParishUpsertOne is the builder for "upsert"-ing
	//  one Parish node.
	ParishUpsertOne struct {
		create *ParishCreate
	}

	// ParishUpsert is the "OnConflict" setter.
	ParishUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *ParishUpsert) SetName(v string) *ParishUpsert {
	u.Set(parish.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ParishUpsert) UpdateName() *ParishUpsert {
	u.SetExcluded(parish.FieldName)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Parish.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(parish.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ParishUpsertOne) UpdateNewValues() *ParishUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(parish.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Parish.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ParishUpsertOne) Ignore() *ParishUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ParishUpsertOne) DoNothing() *ParishUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ParishCreate.OnConflict
// documentation for more info.
func (u *ParishUpsertOne) Update(set func(*ParishUpsert)) *ParishUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ParishUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ParishUpsertOne) SetName(v string) *ParishUpsertOne {
	return u.Update(func(s *ParishUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ParishUpsertOne) UpdateName() *ParishUpsertOne {
	return u.Update(func(s *ParishUpsert) {
		s.UpdateName()
	})
}

// Exec executes the query.
func (u *ParishUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ParishCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ParishUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ParishUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ParishUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ParishCreateBulk is the builder for creating many Parish entities in bulk.
type ParishCreateBulk struct {
	config
	err      error
	builders []*ParishCreate
	conflict []sql.ConflictOption
}

// Save creates the Parish entities in the database.
func (_c *ParishCreateBulk) Save(ctx context.Context) ([]*Parish, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Parish, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ParishMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ParishCreateBulk) SaveX(ctx context.Context) []*Parish {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ParishCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ParishCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Parish.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ParishUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *ParishCreateBulk) OnConflict(opts ...sql.ConflictOption) *ParishUpsertBulk {
	_c.conflict = opts
	return &ParishUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Parish.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ParishCreateBulk) OnConflictColumns(columns ...string) *ParishUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ParishUpsertBulk{
		create: _c,
	}
}

// ParishUpsertBulk is the builder for "upsert"-ing
// a bulk of Parish nodes.
type ParishUpsertBulk struct {
	create *ParishCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Parish.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(parish.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ParishUpsertBulk) UpdateNewValues() *ParishUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(parish.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Parish.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ParishUpsertBulk) Ignore() *ParishUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ParishUpsertBulk) DoNothing() *ParishUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ParishCreateBulk.OnConflict
// documentation for more info.
func (u *ParishUpsertBulk) Update(set func(*ParishUpsert)) *ParishUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ParishUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ParishUpsertBulk) SetName(v string) *ParishUpsertBulk {
	return u.Update(func(s *ParishUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ParishUpsertBulk) UpdateName() *ParishUpsertBulk {
	return u.Update(func(s *ParishUpsert) {
		s.UpdateName()
	})
}

// Exec executes the query.
func (u *ParishUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ParishCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ParishCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ParishUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
