// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/paroki/domus/api/ent/diocese"
	"github.com/paroki/domus/api/ent/internal"
	"github.com/paroki/domus/api/ent/parish"
	"github.com/paroki/domus/api/ent/predicate"
)

// ParishUpdate is the builder for updating Parish entities.
type ParishUpdate struct {
	config
	hooks    []Hook
	mutation *ParishMutation
}

// Where appends a list predicates to the ParishUpdate builder.
func (_u *ParishUpdate) Where(ps ...predicate.Parish) *ParishUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ParishUpdate) SetName(v string) *ParishUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ParishUpdate) SetNillableName(v *string) *ParishUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDioceseID sets the "diocese" edge to the Diocese entity by ID.
func (_u *ParishUpdate) SetDioceseID(id int) *ParishUpdate {
	_u.mutation.SetDioceseID(id)
	return _u
}

// SetNillableDioceseID sets the "diocese" edge to the Diocese entity by ID if the given value is not nil.
func (_u *ParishUpdate) SetNillableDioceseID(id *int) *ParishUpdate {
	if id != nil {
		_u = _u.SetDioceseID(*id)
	}
	return _u
}

// SetDiocese sets the "diocese" edge to the Diocese entity.
func (_u *ParishUpdate) SetDiocese(v *Diocese) *ParishUpdate {
	return _u.SetDioceseID(v.ID)
}

// Mutation returns the ParishMutation object of the builder.
func (_u *ParishUpdate) Mutation() *ParishMutation {
	return _u.mutation
}

// ClearDiocese clears the "diocese" edge to the Diocese entity.
func (_u *ParishUpdate) ClearDiocese() *ParishUpdate {
	_u.mutation.ClearDiocese()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ParishUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ParishUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ParishUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ParishUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ParishUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(parish.Table, parish.Columns, sqlgraph.NewFieldSpec(parish.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(parish.FieldName, field.TypeString, value)
	}
	if _u.mutation.DioceseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   parish.DioceseTable,
			Columns: []string{parish.DioceseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diocese.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Parish
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DioceseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   parish.DioceseTable,
			Columns: []string{parish.DioceseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diocese.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Parish
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Parish
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{parish.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ParishUpdateOne is the builder for updating a single Parish entity.
type ParishUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ParishMutation
}

// SetName sets the "name" field.
func (_u *ParishUpdateOne) SetName(v string) *ParishUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ParishUpdateOne) SetNillableName(v *string) *ParishUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDioceseID sets the "diocese" edge to the Diocese entity by ID.
func (_u *ParishUpdateOne) SetDioceseID(id int) *ParishUpdateOne {
	_u.mutation.SetDioceseID(id)
	return _u
}

// SetNillableDioceseID sets the "diocese" edge to the Diocese entity by ID if the given value is not nil.
func (_u *ParishUpdateOne) SetNillableDioceseID(id *int) *ParishUpdateOne {
	if id != nil {
		_u = _u.SetDioceseID(*id)
	}
	return _u
}

// SetDiocese sets the "diocese" edge to the Diocese entity.
func (_u *ParishUpdateOne) SetDiocese(v *Diocese) *ParishUpdateOne {
	return _u.SetDioceseID(v.ID)
}

// Mutation returns the ParishMutation object of the builder.
func (_u *ParishUpdateOne) Mutation() *ParishMutation {
	return _u.mutation
}

// ClearDiocese clears the "diocese" edge to the Diocese entity.
func (_u *ParishUpdateOne) ClearDiocese() *ParishUpdateOne {
	_u.mutation.ClearDiocese()
	return _u
}

// Where appends a list predicates to the ParishUpdate builder.
func (_u *ParishUpdateOne) Where(ps ...predicate.Parish) *ParishUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ParishUpdateOne) Select(field string, fields ...string) *ParishUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Parish entity.
func (_u *ParishUpdateOne) Save(ctx context.Context) (*Parish, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ParishUpdateOne) SaveX(ctx context.Context) *Parish {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ParishUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ParishUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ParishUpdateOne) sqlSave(ctx context.Context) (_node *Parish, err error) {
	_spec := sqlgraph.NewUpdateSpec(parish.Table, parish.Columns, sqlgraph.NewFieldSpec(parish.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Parish.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, parish.FieldID)
		for _, f := range fields {
			if !parish.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != parish.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(parish.FieldName, field.TypeString, value)
	}
	if _u.mutation.DioceseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   parish.DioceseTable,
			Columns: []string{parish.DioceseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diocese.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Parish
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DioceseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   parish.DioceseTable,
			Columns: []string{parish.DioceseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(diocese.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Parish
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Parish
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Parish{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{parish.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
