// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/paroki/domus/api/ent/diocese"
	"github.com/paroki/domus/api/ent/schema"
	"github.com/paroki/domus/api/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	dioceseMixin := schema.Diocese{}.Mixin()
	dioceseMixinFields0 := dioceseMixin[0].Fields()
	_ = dioceseMixinFields0
	dioceseFields := schema.Diocese{}.Fields()
	_ = dioceseFields
	// dioceseDescCreatedAt is the schema descriptor for createdAt field.
	dioceseDescCreatedAt := dioceseMixinFields0[1].Descriptor()
	// diocese.DefaultCreatedAt holds the default value on creation for the createdAt field.
	diocese.DefaultCreatedAt = dioceseDescCreatedAt.Default.(func() time.Time)
	// dioceseDescUpdatedAt is the schema descriptor for updatedAt field.
	dioceseDescUpdatedAt := dioceseMixinFields0[3].Descriptor()
	// diocese.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	diocese.DefaultUpdatedAt = dioceseDescUpdatedAt.Default.(func() time.Time)
	// diocese.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	diocese.UpdateDefaultUpdatedAt = dioceseDescUpdatedAt.UpdateDefault.(func() time.Time)
	// dioceseDescName is the schema descriptor for name field.
	dioceseDescName := dioceseFields[1].Descriptor()
	// diocese.NameValidator is a validator for the "name" field. It is called by the builders before save.
	diocese.NameValidator = dioceseDescName.Validators[0].(func(string) error)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
