// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/paroki/domus/api/ent/unit"
	"github.com/paroki/domus/api/ent/user"
)

// UnitCreate is the builder for creating a Unit entity.
type UnitCreate struct {
	config
	mutation *UnitMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedBy sets the "createdBy" field.
func (_c *UnitCreate) SetCreatedBy(v uuid.UUID) *UnitCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "createdAt" field.
func (_c *UnitCreate) SetCreatedAt(v time.Time) *UnitCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_c *UnitCreate) SetNillableCreatedAt(v *time.Time) *UnitCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updatedBy" field.
func (_c *UnitCreate) SetUpdatedBy(v uuid.UUID) *UnitCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetUpdatedAt sets the "updatedAt" field.
func (_c *UnitCreate) SetUpdatedAt(v time.Time) *UnitCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (_c *UnitCreate) SetNillableUpdatedAt(v *time.Time) *UnitCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *UnitCreate) SetName(v string) *UnitCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetID sets the "id" field.
func (_c *UnitCreate) SetID(v uuid.UUID) *UnitCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UnitCreate) SetNillableID(v *uuid.UUID) *UnitCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_c *UnitCreate) SetCreatorID(id uuid.UUID) *UnitCreate {
	_c.mutation.SetCreatorID(id)
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *UnitCreate) SetCreator(v *User) *UnitCreate {
	return _c.SetCreatorID(v.ID)
}

// SetUpdaterID sets the "updater" edge to the User entity by ID.
func (_c *UnitCreate) SetUpdaterID(id uuid.UUID) *UnitCreate {
	_c.mutation.SetUpdaterID(id)
	return _c
}

// SetUpdater sets the "updater" edge to the User entity.
func (_c *UnitCreate) SetUpdater(v *User) *UnitCreate {
	return _c.SetUpdaterID(v.ID)
}

// Mutation returns the UnitMutation object of the builder.
func (_c *UnitCreate) Mutation() *UnitMutation {
	return _c.mutation
}

// Save creates the Unit in the database.
func (_c *UnitCreate) Save(ctx context.Context) (*Unit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UnitCreate) SaveX(ctx context.Context) *Unit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UnitCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UnitCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UnitCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := unit.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := unit.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := unit.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UnitCreate) check() error {
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "createdBy", err: errors.New(`ent: missing required field "Unit.createdBy"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "Unit.createdAt"`)}
	}
	if _, ok := _c.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updatedBy", err: errors.New(`ent: missing required field "Unit.updatedBy"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "Unit.updatedAt"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Unit.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := unit.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Unit.name": %w`, err)}
		}
	}
	if len(_c.mutation.CreatorIDs()) == 0 {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required edge "Unit.creator"`)}
	}
	if len(_c.mutation.UpdaterIDs()) == 0 {
		return &ValidationError{Name: "updater", err: errors.New(`ent: missing required edge "Unit.updater"`)}
	}
	return nil
}

func (_c *UnitCreate) sqlSave(ctx context.Context) (*Unit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UnitCreate) createSpec() (*Unit, *sqlgraph.CreateSpec) {
	var (
		_node = &Unit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(unit.Table, sqlgraph.NewFieldSpec(unit.FieldID, field.TypeUUID))
	)
	_spec.Schema = _c.schemaConfig.Unit
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(unit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(unit.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(unit.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   unit.CreatorTable,
			Columns: []string{unit.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _c.schemaConfig.Unit
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UpdaterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   unit.UpdaterTable,
			Columns: []string{unit.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _c.schemaConfig.Unit
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UpdatedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Unit.Create().
//		SetCreatedBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UnitUpsert) {
//			SetCreatedBy(v+v).
//		}).
//		Exec(ctx)
func (_c *UnitCreate) OnConflict(opts ...sql.ConflictOption) *UnitUpsertOne {
	_c.conflict = opts
	return &UnitUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Unit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UnitCreate) OnConflictColumns(columns ...string) *UnitUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UnitUpsertOne{
		create: _c,
	}
}

type (
	// UnitUpsertOne is the builder for "upsert"-ing
	//  one Unit node.
	UnitUpsertOne struct {
		create *UnitCreate
	}

	// UnitUpsert is the "OnConflict" setter.
	UnitUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedBy sets the "createdBy" field.
func (u *UnitUpsert) SetCreatedBy(v uuid.UUID) *UnitUpsert {
	u.Set(unit.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "createdBy" field to the value that was provided on create.
func (u *UnitUpsert) UpdateCreatedBy() *UnitUpsert {
	u.SetExcluded(unit.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updatedBy" field.
func (u *UnitUpsert) SetUpdatedBy(v uuid.UUID) *UnitUpsert {
	u.Set(unit.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updatedBy" field to the value that was provided on create.
func (u *UnitUpsert) UpdateUpdatedBy() *UnitUpsert {
	u.SetExcluded(unit.FieldUpdatedBy)
	return u
}

// SetUpdatedAt sets the "updatedAt" field.
func (u *UnitUpsert) SetUpdatedAt(v time.Time) *UnitUpsert {
	u.Set(unit.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updatedAt" field to the value that was provided on create.
func (u *UnitUpsert) UpdateUpdatedAt() *UnitUpsert {
	u.SetExcluded(unit.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *UnitUpsert) SetName(v string) *UnitUpsert {
	u.Set(unit.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UnitUpsert) UpdateName() *UnitUpsert {
	u.SetExcluded(unit.FieldName)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Unit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(unit.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UnitUpsertOne) UpdateNewValues() *UnitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(unit.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(unit.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Unit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UnitUpsertOne) Ignore() *UnitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UnitUpsertOne) DoNothing() *UnitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UnitCreate.OnConflict
// documentation for more info.
func (u *UnitUpsertOne) Update(set func(*UnitUpsert)) *UnitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UnitUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedBy sets the "createdBy" field.
func (u *UnitUpsertOne) SetCreatedBy(v uuid.UUID) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "createdBy" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateCreatedBy() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedBy sets the "updatedBy" field.
func (u *UnitUpsertOne) SetUpdatedBy(v uuid.UUID) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updatedBy" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateUpdatedBy() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateUpdatedBy()
	})
}

// SetUpdatedAt sets the "updatedAt" field.
func (u *UnitUpsertOne) SetUpdatedAt(v time.Time) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updatedAt" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateUpdatedAt() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *UnitUpsertOne) SetName(v string) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateName() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateName()
	})
}

// Exec executes the query.
func (u *UnitUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UnitCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UnitUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UnitUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: UnitUpsertOne.ID is not supported by MySQL driver. Use UnitUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UnitUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UnitCreateBulk is the builder for creating many Unit entities in bulk.
type UnitCreateBulk struct {
	config
	err      error
	builders []*UnitCreate
	conflict []sql.ConflictOption
}

// Save creates the Unit entities in the database.
func (_c *UnitCreateBulk) Save(ctx context.Context) ([]*Unit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Unit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UnitMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UnitCreateBulk) SaveX(ctx context.Context) []*Unit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UnitCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UnitCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Unit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UnitUpsert) {
//			SetCreatedBy(v+v).
//		}).
//		Exec(ctx)
func (_c *UnitCreateBulk) OnConflict(opts ...sql.ConflictOption) *UnitUpsertBulk {
	_c.conflict = opts
	return &UnitUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Unit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UnitCreateBulk) OnConflictColumns(columns ...string) *UnitUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UnitUpsertBulk{
		create: _c,
	}
}

// UnitUpsertBulk is the builder for "upsert"-ing
// a bulk of Unit nodes.
type UnitUpsertBulk struct {
	create *UnitCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Unit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(unit.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UnitUpsertBulk) UpdateNewValues() *UnitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(unit.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(unit.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Unit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UnitUpsertBulk) Ignore() *UnitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UnitUpsertBulk) DoNothing() *UnitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UnitCreateBulk.OnConflict
// documentation for more info.
func (u *UnitUpsertBulk) Update(set func(*UnitUpsert)) *UnitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UnitUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedBy sets the "createdBy" field.
func (u *UnitUpsertBulk) SetCreatedBy(v uuid.UUID) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "createdBy" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateCreatedBy() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedBy sets the "updatedBy" field.
func (u *UnitUpsertBulk) SetUpdatedBy(v uuid.UUID) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updatedBy" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateUpdatedBy() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateUpdatedBy()
	})
}

// SetUpdatedAt sets the "updatedAt" field.
func (u *UnitUpsertBulk) SetUpdatedAt(v time.Time) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updatedAt" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateUpdatedAt() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *UnitUpsertBulk) SetName(v string) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateName() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateName()
	})
}

// Exec executes the query.
func (u *UnitUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UnitCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UnitCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UnitUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
