// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/paroki/domus/api/ent/internal"
	"github.com/paroki/domus/api/ent/predicate"
	"github.com/paroki/domus/api/ent/unit"
	"github.com/paroki/domus/api/ent/user"
)

// UnitUpdate is the builder for updating Unit entities.
type UnitUpdate struct {
	config
	hooks    []Hook
	mutation *UnitMutation
}

// Where appends a list predicates to the UnitUpdate builder.
func (_u *UnitUpdate) Where(ps ...predicate.Unit) *UnitUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatedBy sets the "createdBy" field.
func (_u *UnitUpdate) SetCreatedBy(v uuid.UUID) *UnitUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "createdBy" field if the given value is not nil.
func (_u *UnitUpdate) SetNillableCreatedBy(v *uuid.UUID) *UnitUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updatedBy" field.
func (_u *UnitUpdate) SetUpdatedBy(v uuid.UUID) *UnitUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updatedBy" field if the given value is not nil.
func (_u *UnitUpdate) SetNillableUpdatedBy(v *uuid.UUID) *UnitUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *UnitUpdate) SetUpdatedAt(v time.Time) *UnitUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *UnitUpdate) SetName(v string) *UnitUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UnitUpdate) SetNillableName(v *string) *UnitUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *UnitUpdate) SetDescription(v string) *UnitUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *UnitUpdate) SetNillableDescription(v *string) *UnitUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *UnitUpdate) SetCreatorID(id uuid.UUID) *UnitUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *UnitUpdate) SetCreator(v *User) *UnitUpdate {
	return _u.SetCreatorID(v.ID)
}

// SetUpdaterID sets the "updater" edge to the User entity by ID.
func (_u *UnitUpdate) SetUpdaterID(id uuid.UUID) *UnitUpdate {
	_u.mutation.SetUpdaterID(id)
	return _u
}

// SetUpdater sets the "updater" edge to the User entity.
func (_u *UnitUpdate) SetUpdater(v *User) *UnitUpdate {
	return _u.SetUpdaterID(v.ID)
}

// SetParentID sets the "parent" edge to the Unit entity by ID.
func (_u *UnitUpdate) SetParentID(id int) *UnitUpdate {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Unit entity by ID if the given value is not nil.
func (_u *UnitUpdate) SetNillableParentID(id *int) *UnitUpdate {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Unit entity.
func (_u *UnitUpdate) SetParent(v *Unit) *UnitUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Unit entity by IDs.
func (_u *UnitUpdate) AddChildIDs(ids ...int) *UnitUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Unit entity.
func (_u *UnitUpdate) AddChildren(v ...*Unit) *UnitUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the UnitMutation object of the builder.
func (_u *UnitUpdate) Mutation() *UnitMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *UnitUpdate) ClearCreator() *UnitUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// ClearUpdater clears the "updater" edge to the User entity.
func (_u *UnitUpdate) ClearUpdater() *UnitUpdate {
	_u.mutation.ClearUpdater()
	return _u
}

// ClearParent clears the "parent" edge to the Unit entity.
func (_u *UnitUpdate) ClearParent() *UnitUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the Unit entity.
func (_u *UnitUpdate) ClearChildren() *UnitUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Unit entities by IDs.
func (_u *UnitUpdate) RemoveChildIDs(ids ...int) *UnitUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Unit entities.
func (_u *UnitUpdate) RemoveChildren(v ...*Unit) *UnitUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UnitUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UnitUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UnitUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UnitUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UnitUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := unit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UnitUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := unit.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Unit.name": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Unit.creator"`)
	}
	if _u.mutation.UpdaterCleared() && len(_u.mutation.UpdaterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Unit.updater"`)
	}
	return nil
}

func (_u *UnitUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(unit.Table, unit.Columns, sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(unit.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(unit.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(unit.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   unit.CreatorTable,
			Columns: []string{unit.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Unit
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   unit.CreatorTable,
			Columns: []string{unit.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Unit
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UpdaterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   unit.UpdaterTable,
			Columns: []string{unit.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Unit
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpdaterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   unit.UpdaterTable,
			Columns: []string{unit.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Unit
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unit.ParentTable,
			Columns: []string{unit.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Unit
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unit.ParentTable,
			Columns: []string{unit.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Unit
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unit.ChildrenTable,
			Columns: []string{unit.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Unit
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unit.ChildrenTable,
			Columns: []string{unit.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Unit
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unit.ChildrenTable,
			Columns: []string{unit.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Unit
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Unit
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{unit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UnitUpdateOne is the builder for updating a single Unit entity.
type UnitUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UnitMutation
}

// SetCreatedBy sets the "createdBy" field.
func (_u *UnitUpdateOne) SetCreatedBy(v uuid.UUID) *UnitUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "createdBy" field if the given value is not nil.
func (_u *UnitUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *UnitUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updatedBy" field.
func (_u *UnitUpdateOne) SetUpdatedBy(v uuid.UUID) *UnitUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updatedBy" field if the given value is not nil.
func (_u *UnitUpdateOne) SetNillableUpdatedBy(v *uuid.UUID) *UnitUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *UnitUpdateOne) SetUpdatedAt(v time.Time) *UnitUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *UnitUpdateOne) SetName(v string) *UnitUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UnitUpdateOne) SetNillableName(v *string) *UnitUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *UnitUpdateOne) SetDescription(v string) *UnitUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *UnitUpdateOne) SetNillableDescription(v *string) *UnitUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *UnitUpdateOne) SetCreatorID(id uuid.UUID) *UnitUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *UnitUpdateOne) SetCreator(v *User) *UnitUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// SetUpdaterID sets the "updater" edge to the User entity by ID.
func (_u *UnitUpdateOne) SetUpdaterID(id uuid.UUID) *UnitUpdateOne {
	_u.mutation.SetUpdaterID(id)
	return _u
}

// SetUpdater sets the "updater" edge to the User entity.
func (_u *UnitUpdateOne) SetUpdater(v *User) *UnitUpdateOne {
	return _u.SetUpdaterID(v.ID)
}

// SetParentID sets the "parent" edge to the Unit entity by ID.
func (_u *UnitUpdateOne) SetParentID(id int) *UnitUpdateOne {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Unit entity by ID if the given value is not nil.
func (_u *UnitUpdateOne) SetNillableParentID(id *int) *UnitUpdateOne {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Unit entity.
func (_u *UnitUpdateOne) SetParent(v *Unit) *UnitUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Unit entity by IDs.
func (_u *UnitUpdateOne) AddChildIDs(ids ...int) *UnitUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Unit entity.
func (_u *UnitUpdateOne) AddChildren(v ...*Unit) *UnitUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the UnitMutation object of the builder.
func (_u *UnitUpdateOne) Mutation() *UnitMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *UnitUpdateOne) ClearCreator() *UnitUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// ClearUpdater clears the "updater" edge to the User entity.
func (_u *UnitUpdateOne) ClearUpdater() *UnitUpdateOne {
	_u.mutation.ClearUpdater()
	return _u
}

// ClearParent clears the "parent" edge to the Unit entity.
func (_u *UnitUpdateOne) ClearParent() *UnitUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the Unit entity.
func (_u *UnitUpdateOne) ClearChildren() *UnitUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Unit entities by IDs.
func (_u *UnitUpdateOne) RemoveChildIDs(ids ...int) *UnitUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Unit entities.
func (_u *UnitUpdateOne) RemoveChildren(v ...*Unit) *UnitUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Where appends a list predicates to the UnitUpdate builder.
func (_u *UnitUpdateOne) Where(ps ...predicate.Unit) *UnitUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UnitUpdateOne) Select(field string, fields ...string) *UnitUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Unit entity.
func (_u *UnitUpdateOne) Save(ctx context.Context) (*Unit, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UnitUpdateOne) SaveX(ctx context.Context) *Unit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UnitUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UnitUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UnitUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := unit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UnitUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := unit.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Unit.name": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Unit.creator"`)
	}
	if _u.mutation.UpdaterCleared() && len(_u.mutation.UpdaterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Unit.updater"`)
	}
	return nil
}

func (_u *UnitUpdateOne) sqlSave(ctx context.Context) (_node *Unit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(unit.Table, unit.Columns, sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Unit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, unit.FieldID)
		for _, f := range fields {
			if !unit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != unit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(unit.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(unit.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(unit.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   unit.CreatorTable,
			Columns: []string{unit.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Unit
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   unit.CreatorTable,
			Columns: []string{unit.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Unit
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UpdaterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   unit.UpdaterTable,
			Columns: []string{unit.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Unit
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpdaterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   unit.UpdaterTable,
			Columns: []string{unit.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.Unit
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unit.ParentTable,
			Columns: []string{unit.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Unit
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unit.ParentTable,
			Columns: []string{unit.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Unit
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unit.ChildrenTable,
			Columns: []string{unit.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Unit
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unit.ChildrenTable,
			Columns: []string{unit.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Unit
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unit.ChildrenTable,
			Columns: []string{unit.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeInt),
			},
		}
		edge.Schema = _u.schemaConfig.Unit
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Unit
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Unit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{unit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
