// Code generated by ent, DO NOT EDIT.

package parish

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the parish type in the database.
	Label = "parish"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeDiocese holds the string denoting the diocese edge name in mutations.
	EdgeDiocese = "diocese"
	// Table holds the table name of the parish in the database.
	Table = "parishes"
	// DioceseTable is the table that holds the diocese relation/edge.
	DioceseTable = "parishes"
	// DioceseInverseTable is the table name for the Diocese entity.
	// It exists in this package in order to avoid circular dependency with the "diocese" package.
	DioceseInverseTable = "dioceses"
	// DioceseColumn is the table column denoting the diocese relation/edge.
	DioceseColumn = "diocese_parishes"
)

// Columns holds all SQL columns for parish fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "parishes"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"diocese_parishes",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Parish queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDioceseField orders the results by diocese field.
func ByDioceseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDioceseStep(), sql.OrderByField(field, opts...))
	}
}
func newDioceseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DioceseInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DioceseTable, DioceseColumn),
	)
}
