/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/dioceses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get all dioceses
     * @description Get all dioceses list
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.WebResponse-array_model_DioceseResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
      };
    };
    put?: never;
    /**
     * Create diocese
     * @description Create a new diocese
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Create diocese request */
      requestBody: {
        content: {
          "application/json": components["schemas"]["model.CreateDioceseRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.WebResponse-model_DioceseResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Unprocessable Entity */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/dioceses/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get diocese by ID
     * @description Get diocese details by ID
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Diocese ID */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.WebResponse-model_DioceseResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Update diocese
     * @description Update diocese by ID
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Diocese ID */
          id: number;
        };
        cookie?: never;
      };
      /** @description Update diocese request */
      requestBody: {
        content: {
          "application/json": components["schemas"]["model.UpdateDioceseRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.WebResponse-model_DioceseResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Unprocessable Entity */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
      };
    };
    post?: never;
    /**
     * Delete diocese
     * @description Delete diocese by ID
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Diocese ID */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/parishes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get all parishes
     * @description Get all parishes list
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.WebResponse-array_model_ParishResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
      };
    };
    put?: never;
    /**
     * Create parish
     * @description Create a new parish
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Create parish request */
      requestBody: {
        content: {
          "application/json": components["schemas"]["model.CreateParishRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.WebResponse-model_ParishResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Unprocessable Entity */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/parishes/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get parish by ID
     * @description Get parish details by ID
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Parish ID */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.WebResponse-model_ParishResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Update parish
     * @description Update parish by ID
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Parish ID */
          id: number;
        };
        cookie?: never;
      };
      /** @description Update parish request */
      requestBody: {
        content: {
          "application/json": components["schemas"]["model.UpdateParishRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.WebResponse-model_ParishResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Unprocessable Entity */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
      };
    };
    post?: never;
    /**
     * Delete parish
     * @description Delete parish by ID
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Parish ID */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ping": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check ping
     * @description Returns current authenticated user information from context
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.WebResponse-core_AuthenticatedUser"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["httpx.ErrorResponse"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    "core.AuthenticatedUser": {
      avatar?: string;
      email?: string;
      id?: string;
      name?: string;
      roles?: components["schemas"]["core.UserRole"][];
      scope?: string;
    };
    "core.User": {
      avatar?: string;
      createdAt?: string;
      email?: string;
      id?: string;
      name?: string;
      updatedAt?: string;
    };
    /** @enum {string} */
    "core.UserRole": "admin" | "superadmin" | "user";
    "httpx.ErrorBody": {
      code?: string;
      fields?: components["schemas"]["httpx.FieldError"][];
      message?: string;
    };
    "httpx.ErrorResponse": {
      error?: components["schemas"]["httpx.ErrorBody"];
      meta?: components["schemas"]["httpx.Meta"];
    };
    "httpx.FieldError": {
      field?: string;
      rule?: string;
    };
    "httpx.Meta": {
      cursor?: string;
      requestId?: string;
      timestamp?: string;
    };
    "httpx.WebResponse-array_model_DioceseResponse": {
      data?: components["schemas"]["model.DioceseResponse"][];
      meta?: components["schemas"]["httpx.Meta"];
    };
    "httpx.WebResponse-array_model_ParishResponse": {
      data?: components["schemas"]["model.ParishResponse"][];
      meta?: components["schemas"]["httpx.Meta"];
    };
    "httpx.WebResponse-core_AuthenticatedUser": {
      data?: components["schemas"]["core.AuthenticatedUser"];
      meta?: components["schemas"]["httpx.Meta"];
    };
    "httpx.WebResponse-model_DioceseResponse": {
      data?: components["schemas"]["model.DioceseResponse"];
      meta?: components["schemas"]["httpx.Meta"];
    };
    "httpx.WebResponse-model_ParishResponse": {
      data?: components["schemas"]["model.ParishResponse"];
      meta?: components["schemas"]["httpx.Meta"];
    };
    "model.CreateDioceseRequest": {
      name: string;
    };
    "model.CreateParishRequest": {
      dioceseId?: number;
      name: string;
    };
    "model.DioceseResponse": {
      createdAt?: string;
      createdBy?: components["schemas"]["core.User"];
      id?: number;
      name?: string;
      updatedAt?: string;
      updatedBy?: components["schemas"]["core.User"];
    };
    "model.ParishResponse": {
      diocese?: components["schemas"]["model.DioceseResponse"];
      id?: number;
      name?: string;
    };
    "model.UpdateDioceseRequest": {
      name: string;
    };
    "model.UpdateParishRequest": {
      dioceseId?: number;
      name: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
