// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Unit is the predicate function for unit builders.
type Unit func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
